# Generated by Django 4.1.1 on 2022-09-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0003_alter_message_options_alter_room_options_room_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
